# Inserts a blank line between shell prompts
add_newline = false

format = """
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$custom\
$fill\
$cmd_duration\
$line_break\
$status\
$character"""

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
format = "[$path]($style) "

[fill]
symbol = " "

[git_branch]
symbol = ""
format = "[$branch]($style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
format = "[$all_status$ahead_behind]($style)"

[cmd_duration]
min_time = 500
format = "[$duration]($style)"
